/**
 * TSL node material node list: categories and node types for the left panel.
 * Each node has: id (React Flow type id), label (display name).
 * Inputs/outputs are defined per type in nodeDefinitions.js or in the component.
 */
export const NODE_CATEGORIES = [
  {
    id: 'advanced',
    label: 'Advanced',
    nodes: [
      { id: 'group', label: 'Group' },
      { id: 'frontFacing', label: 'Front Facing' },
      { id: 'hashBlur', label: 'Hash Blur' },
      { id: 'linearDepth', label: 'Linear Depth' },
      { id: 'linearDepthFrom', label: 'Linear Depth (From)' },
      { id: 'output', label: 'Output' },
      { id: 'var', label: 'Var' },
      { id: 'varying', label: 'Varying' },
      { id: 'viewportLinearDepth', label: 'Viewport Linear Depth' },
    ],
  },
  {
    id: 'constants',
    label: 'Constants',
    nodes: [
      { id: 'color', label: 'Color' },
      { id: 'float', label: 'Float' },
      { id: 'int', label: 'Int' },
      { id: 'vec2', label: 'Vec2' },
      { id: 'vec3', label: 'Vec3' },
      { id: 'vec4', label: 'Vec4' },
    ],
  },
  {
    id: 'geometry',
    label: 'Geometry',
    nodes: [
      { id: 'instanceCount', label: 'Instance Count' },
      { id: 'instanceIndex', label: 'Instance Index' },
      { id: 'normalLocal', label: 'Normal Local' },
      { id: 'normalView', label: 'Normal View' },
      { id: 'normalWorld', label: 'Normal World' },
      { id: 'positionLocal', label: 'Position Local' },
      { id: 'positionView', label: 'Position View' },
      { id: 'positionViewDirection', label: 'Position View Direction' },
      { id: 'positionWorld', label: 'Position World' },
      { id: 'resolution', label: 'Resolution' },
      { id: 'screenUV', label: 'Screen UV' },
      { id: 'tangentLocal', label: 'Tangent Local' },
      { id: 'time', label: 'Time' },
      { id: 'uv', label: 'UV' },
    ],
  },
  {
    id: 'logic',
    label: 'Logic',
    nodes: [
      { id: 'and', label: 'And' },
      { id: 'discard', label: 'Discard' },
      { id: 'greaterEqual', label: 'Greater Equal' },
      { id: 'greaterThan', label: 'Greater Than' },
      { id: 'lessEqual', label: 'Less Equal' },
      { id: 'lessThan', label: 'Less Than' },
      { id: 'not', label: 'Not' },
      { id: 'or', label: 'Or' },
      { id: 'select', label: 'Select' },
      { id: 'xor', label: 'Xor' },
    ],
  },
  {
    id: 'material',
    label: 'Material',
    nodes: [
      { id: 'meshBasicMaterial', label: 'MeshBasicMaterial' },
      { id: 'meshPhongMaterial', label: 'MeshPhongMaterial' },
      { id: 'meshPhysicalMaterial', label: 'MeshPhysicalMaterial' },
      { id: 'meshStandardMaterial', label: 'MeshStandardMaterial' },
      { id: 'meshSSSMaterial', label: 'MeshSSSMaterial' },
      { id: 'meshToonMaterial', label: 'MeshToonMaterial' },
      { id: 'meshLambertMaterial', label: 'MeshLambertMaterial' },
      { id: 'meshNormalMaterial', label: 'MeshNormalMaterial' },
      { id: 'pointsMaterial', label: 'PointsMaterial' },
      { id: 'spriteNodeMaterial', label: 'SpriteNodeMaterial' },
    ],
  },
  {
    id: 'math',
    label: 'Math',
    nodes: [
      { id: 'oneMinusX', label: '1 - X' },
      { id: 'oneDivX', label: '1 / X' },
      { id: 'abs', label: 'Abs' },
      { id: 'acos', label: 'ACos' },
      { id: 'add', label: 'Add' },
      { id: 'all', label: 'All' },
      { id: 'any', label: 'Any' },
      { id: 'asin', label: 'ASin' },
      { id: 'atan', label: 'ATan' },
      { id: 'cbrt', label: 'Cbrt' },
      { id: 'ceil', label: 'Ceil' },
      { id: 'clamp', label: 'Clamp' },
      { id: 'cos', label: 'Cos' },
      { id: 'cross', label: 'Cross' },
      { id: 'degrees', label: 'Degrees' },
      { id: 'dfdx', label: 'dFdx' },
      { id: 'dfdy', label: 'dFdy' },
      { id: 'difference', label: 'Difference' },
      { id: 'distance', label: 'Distance' },
      { id: 'divide', label: 'Divide' },
      { id: 'dot', label: 'Dot' },
      { id: 'epsilon', label: 'Epsilon' },
      { id: 'equals', label: 'Equals' },
      { id: 'exp', label: 'Exp' },
      { id: 'exp2', label: 'Exp2' },
      { id: 'faceForward', label: 'Face Forward' },
      { id: 'floor', label: 'Floor' },
      { id: 'fract', label: 'Fract' },
      { id: 'fwidth', label: 'fwidth' },
      { id: 'halfPi', label: 'Half PI' },
      { id: 'infinity', label: 'Infinity' },
      { id: 'inverseSqrt', label: 'Inverse Sqrt' },
      { id: 'length', label: 'Length' },
      { id: 'log', label: 'Log' },
      { id: 'log2', label: 'Log2' },
      { id: 'max', label: 'Max' },
      { id: 'min', label: 'Min' },
      { id: 'mix', label: 'Mix' },
      { id: 'mod', label: 'Mod' },
      { id: 'multiOp', label: 'Multi-op' },
      { id: 'multiply', label: 'Multiply' },
      { id: 'negate', label: 'Negate' },
      { id: 'normalize', label: 'Normalize' },
      { id: 'pi', label: 'PI' },
      { id: 'pow2', label: 'Pow2' },
      { id: 'pow3', label: 'Pow3' },
      { id: 'pow4', label: 'Pow4' },
      { id: 'power', label: 'Power' },
      { id: 'radians', label: 'Radians' },
      { id: 'range', label: 'Range' },
      { id: 'reflect', label: 'Reflect' },
      { id: 'refract', label: 'Refract' },
      { id: 'remap', label: 'Remap' },
      { id: 'remapClamp', label: 'Remap Clamp' },
      { id: 'round', label: 'Round' },
      { id: 'saturate', label: 'Saturate' },
      { id: 'sign', label: 'Sign' },
      { id: 'sin', label: 'Sin' },
      { id: 'smoothstep', label: 'Smoothstep' },
      { id: 'split', label: 'Split' },
      { id: 'sqrt', label: 'Sqrt' },
      { id: 'step', label: 'Step' },
      { id: 'subtract', label: 'Subtract' },
      { id: 'tan', label: 'Tan' },
      { id: 'trunc', label: 'Trunc' },
      { id: 'twoPi', label: 'Two PI' },
    ],
  },
  {
    id: 'model',
    label: 'Model',
    nodes: [
      { id: 'modelDirection', label: 'Model Direction' },
      { id: 'modelNormalMatrix', label: 'Model Normal Matrix' },
      { id: 'modelPosition', label: 'Model Position' },
      { id: 'modelScale', label: 'Model Scale' },
      { id: 'modelViewMatrix', label: 'Model View Matrix' },
      { id: 'modelViewPosition', label: 'Model View Position' },
      { id: 'modelWorldMatrix', label: 'Model World Matrix' },
    ],
  },
  {
    id: 'noise',
    label: 'Noise',
    nodes: [
      { id: 'cellNoiseFloat', label: 'Cell Noise (Float)' },
      { id: 'fractalNoiseFloat', label: 'Fractal Noise (Float)' },
      { id: 'fractalNoiseVec2', label: 'Fractal Noise (Vec2)' },
      { id: 'fractalNoiseVec3', label: 'Fractal Noise (Vec3)' },
      { id: 'fractalNoiseVec4', label: 'Fractal Noise (Vec4)' },
      { id: 'interleavedGradientNoise', label: 'Interleaved Gradient Noise' },
      { id: 'noiseFloat', label: 'Noise (Float)' },
      { id: 'noiseVec3', label: 'Noise (Vec3)' },
      { id: 'noiseVec4', label: 'Noise (Vec4)' },
      { id: 'triNoise3d', label: 'Tri Noise 3D' },
      { id: 'unifiedNoise2d', label: 'Unified Noise 2D' },
      { id: 'unifiedNoise3d', label: 'Unified Noise 3D' },
      { id: 'worleyNoiseFloat', label: 'Worley Noise (Float)' },
      { id: 'worleyNoiseVec2', label: 'Worley Noise (Vec2)' },
      { id: 'worleyNoiseVec3', label: 'Worley Noise (Vec3)' },
    ],
  },
  {
    id: 'texture',
    label: 'Texture',
    nodes: [
      { id: 'backdrop', label: 'Backdrop' },
      { id: 'texture', label: 'Texture' },
      { id: 'triplanarTexture', label: 'Triplanar Texture' },
      { id: 'viewportDepth', label: 'Viewport Depth' },
    ],
  },
  {
    id: 'utils',
    label: 'Utils',
    nodes: [
      { id: 'checker', label: 'Checker' },
      { id: 'fresnel', label: 'Fresnel' },
      { id: 'hue', label: 'Hue' },
      { id: 'luminance', label: 'Luminance' },
      { id: 'posterize', label: 'Posterize' },
      { id: 'remapUtils', label: 'Remap' },
      { id: 'remapClampUtils', label: 'Remap Clamp' },
      { id: 'rotation2d', label: 'Rotation 2D' },
      { id: 'rotation3d', label: 'Rotation 3D' },
      { id: 'saturation', label: 'Saturation' },
      { id: 'transformDir', label: 'Transform Dir' },
      { id: 'uvTransform', label: 'UV Transform' },
      { id: 'vibrance', label: 'Vibrance' },
    ],
  },
  {
    id: 'custom',
    label: 'Custom Nodes',
    nodes: [
      { id: 'createFromCode', label: 'Create from Code...' },
    ],
  },
];
